### PR TITLE
Enhancement Hide/Show Element with conditional switch

### PR DESCRIPTION
**Pull request by maheshwaghmare**
## Enhancement `Hide/Show Element`

Updated `Hide/Show element` logic with conditional switch. So, We will apply dependency for element by conditions.

E.g.
```
Field-1    !=    Option 2
Field-2    ==    true
Field-3    >=    300
etc.
```

## Added `show-if-operator`

Added `show-if-operator` to apply conditional logic to the element. E.g.

```
<p class="layers-form-item">
	<?php echo $this->form_elements()->input(
		array(
			'type' => 'text',
			'name' => $this->get_layers_field_name( 'field-4' ) ,
			'id' => $this->get_layers_field_id( 'field-4' ) ,
			'value' => ( isset( $widget['field-4'] ) ) ? $widget['field-4'] : NULL,
			'class' => 'layers-text layers-large',
			'data' => array(
				'show-if-selector' => '#' . $this->get_layers_field_id( 'field-3' ),
				'show-if-operator' => '==',
				'show-if-value' => 'true',
			),
		)
	); ?>
</p>
```

Here, `field-4` is visible, If `field-3` checkbox it ticked / checked.

---------

## Added Conditional Operators

Now, Added blow few `conditional operators` and working well. We will add other operators as needed.

```==
===
>=
<=
!=
!==
```

## Tested Layers Inputs

Tested layers [inputs](http://docs.layerswp.com/reference/input/#types) elements `checkbox`, `text`, `select`.

-----------

## Remove Unwanted Code

Please, Remove the below code from file `layerswp\core\assets\admin.js` Line - `641 - 648` after review.

```
console.clear();
console.log('is_true: ' + $is_true );
console.log('target_value: ' + $target_value );
console.log('source_operator: ' + $source_operator );
console.log('source_element_value: ' + $source_element_value );

/** UPDATE TEMPORARY ANIMATION ALWAYS TRUE */
animation_type = 'slideDown';
```

## Live Testing

Created the testing widget `Test Hide / Show` for testing `conditional logic` in github branch `switch_hide_show`. Checkout to branch `switch_hide_show` - ([https://github.com/maheshwaghmare/layerswp/tree/switch_hide_show](https://github.com/maheshwaghmare/layerswp/tree/switch_hide_show)) to test conditional logic.

### Example

1) **Showing**  `Google Map Zoom Level` element. Cause, Checkbox `Show Google Map` is **Checked**.

checkbox-1

----------

2) **Hide**  `Google Map Zoom Level` element. Cause, Checkbox `Show Google Map` is **Not Checked**.

checkbox-2

----------

### CODE REVIEW

**Comment by maheshwaghmare** [comment]
Hay. It's unbelievable and surprising :flushed: coincidence. Yesterday, I was built the `show-if-operator` logic on my localhost while developing my `cf7-designer` widget. And send this pull request.

But, @StuartOB  was already working on this with almost same logic :thought_balloon: in branch:

https://github.com/Obox/layerswp/tree/add-show-if-operator/

It's :open_mouth: unbelievable and surprising :thinking_face: .

**Comment by marcperel** [comment]
:)

**Comment by marcperel** [comment]
@maheshwaghmare I completed it today:

https://github.com/Obox/layerswp/commit/7203fce9de19d59aa872efe8ecaae29d449345d5

**Comment by maheshwaghmare** [comment]
Yep...! This is one of the **Best Feature** of Layers for **Developers & End Users**. It provide better UX for End User & Developer's will do lots of things. Just waiting for master branch in which this changes merge.

So, There is no need of this pull request. Now, I close this pull request. :+1:  Thanks @marcperel & @StuartOB.

**Pull request closed without merging**
