### PR TITLE
Some improvements for translations & German translation added

### PR DESCRIPTION
**Pull request by tmconnect**
There are some strings that can't be translated because they aren't translation ready.

In addition some strings got the wrong translation domain.

Some of the sprintf-functions are changed because they include URLs in the translated string. This will cause a new translation if the URL is changed in the futere. I think the change is a better solution so the strings are now also translateable with the "CodeStyling Localization" plugin.

Sorry, but this translation is better than this pull request https://github.com/Obox/layerswp/pull/11

### CODE REVIEW

**Comment by AndreasWebdev** [comment]
No need to sorry I just translated the project because it was possible and no one else did ;)

**Comment by luizbills** [comment]
:+1:

**Comment by marcperel** [comment]
Thomas, there's one thing that I'd like to point out, in core/options-panel/init.php you've removed the sprintf(), but I'd like to point out that the reasoning behind it is to avoid hardcoded links, which comes up in the theme checker, so I'm going to leave those in.

**Comment by regenrek** [comment]
@marcperel  Did you miss out this pull request https://github.com/tmconnect/layerswp/commit/f99c294732cb90cd94268ee10b1fd2b3f980dfa5  ?
I think this is a far better german translation than the current one.

**Comment by marcperel** [comment]
Oh great thanks Kevin we'll check that out.

**Pull request closed without merging**
