### PR TITLE
Changing the logic of the title and excerpt output

### PR DESCRIPTION
**Pull request by avato**
Currently the logic outputs that if there is no title and no excerpt then the condition is true. 

This result in nothing showing if only one of the conditions are met. 

Changing this will result in the title or excerpt showing if only one holds content and not the other.

### CODE REVIEW

**Comment by marcperel** [comment]
@avato Thanks for the PR, could it be possible next time to please add any PRs to `develop` ? Thanks

**Comment by avato** [comment]
Apologies for that. Should i redo?

**Comment by marcperel** [comment]
The change is pretty simple, I'll just include it myself, thanks @avato

**Comment by marcperel** [comment]
See https://github.com/Obox/layerswp/commit/b699df5781493264c02fa1ccf17628ef97766646

**Pull request closed without merging**
